# Stage 1: Build the application
FROM maven AS build

WORKDIR /app

# Copy source files and the project descriptor to the container
COPY ./backend/src ./src
COPY ./backend/pom.xml .

# Compile the application
RUN mvn clean package -DskipTests

# Stage 2: Create the final Docker image with only the compiled jar and runtime
FROM openjdk:23-jdk-slim

# Copy the jar from the build stage
COPY --from=build /app/target/webapp15-0.0.1-SNAPSHOT.jar java-app.jar

# Specify the container's entrypoint
CMD [ "java", "-jar", "java-app.jar" ]