services:
  java_app:
    container_name: java_app
    image: jgar2020/java_app:1.0
    ports:
      - 8443:8443
    environment:
      SERVER_PORT: 8443
      SECURITY_USER: user
      SECURITY_PASSWORD: $2a$12$OBs4H1WTkCbB43sWjm2P2.F/IyDPVTgVnX0JcG1.hg0C0lCJSuDAi
      DATABASE_URL: jdbc:mysql://app_db/mydb
      DATABASE_USER: grupo15
      DATABASE_PASSWORD: Password123.
    restart: always
    depends_on:
      - app_db

  app_db:
    image: mysql
    environment:
      MYSQL_USER: grupo15
      MYSQL_PASSWORD: Password123.
      MYSQL_ROOT_PASSWORD: RootPassword123. # This is required
      MYSQL_DATABASE: mydb
#     volumes:
#       - mysql:/var/lib/mysql
  
# volumes:
#   mysql: